# Production profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Never auto-update schema in production

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.hackathon.safenet: INFO
    org.springframework.security: INFO
  file:
    name: /var/log/safenet/application.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB