openapi: 3.0.3
info:
  title: MeteoAlarm Germany API
  description: REST API for weather alerts from MeteoAlarm Germany
  version: 1.0.0
servers:
  - url: /api/weather
paths:
  /alerts/english:
    get:
      summary: Get weather alerts in English
      description: Fetches current weather alerts from MeteoAlarm Germany RSS feed and returns them in JSON format with English descriptions.
      tags:
        - MeteoAlarm
      responses:
        '200':
          description: Successfully retrieved weather alerts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeteoAlarmResponse'
              example:
                title: MeteoAlarm Germany
                description: MeteoAlarm - Warnings from Germany
                link: "https://meteoalarm.org?region=DE"
                language: en
                ttl: 10
                items:
                  - title: Germany
                    description: "<table border=\"0\" cellspacing=\"0\" cellpadding=\"3\"><tr><th colspan=\"1\" align=\"left\">Today</th><td width=\"28\">&nbsp;&nbsp;</td><th colspan=\"1\" align=\"left\">Tomorrow</th></tr><tr><td data-awareness-level=\"2\" data-awareness-type=\"4\" width=\"28\">awt:4 level:2</td><td width=\"28\">&nbsp;&nbsp;</td><td width=\"28\"></td></tr></table>"
                    link: "https://meteoalarm.org?region=DE"
                    guid: 8d1dd759657f83eb4cd61b78adbff9e3
                    pubDate: "2025-10-15T05:28:00"
                    region: Germany
                    awarenessLevel: 2
                    awarenessType: 4
                    validFrom: null
                    validUntil: null
                    language: english
                  - title: Kreis Breisgau-Hochschwarzwald und Stadt Freiburg
                    description: "There is a risk of fog (level 1 of 1). Visibility: < 150 m Hazard(s) to expect: severely reduced visibility possible.  Recommendations for what to do:  Adapt your driving behaviour to sudden reduced visibility (fog banks)."
                    link: "https://meteoalarm.org?geocode=EMMA_ID:DE035"
                    guid: 2d898d0fa322d03a4f641b5c327a4074
                    pubDate: "2025-10-15T04:22:00"
                    region: Kreis Breisgau-Hochschwarzwald und Stadt Freiburg
                    awarenessLevel: 2
                    awarenessType: 4
                    validFrom: "2025-10-15T03:17:00"
                    validUntil: "2025-10-15T08:00:00"
                    language: english
        '500':
          description: Internal server error while fetching weather data
  /alerts/german:
    get:
      summary: Get weather alerts in German
      description: Fetches current weather alerts from MeteoAlarm Germany RSS feed and returns them in JSON format with German descriptions.
      tags:
        - MeteoAlarm
      responses:
        '200':
          description: Successfully retrieved weather alerts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeteoAlarmResponse'
              example:
                title: MeteoAlarm Germany
                description: MeteoAlarm - Warnungen aus Deutschland
                link: "https://meteoalarm.org?region=DE"
                language: de
                ttl: 10
                items:
                  - title: Kreis Breisgau-Hochschwarzwald und Stadt Freiburg
                    description: "Es besteht Nebelgefahr (Stufe 1 von 1). Sichtweite: < 150 m Erwartete Gefahr(en): stark eingeschränkte Sicht möglich.  Empfehlungen:  Passen Sie Ihr Fahrverhalten plötzlicher Sichtbehinderung (Nebelbänke) an."
                    link: "https://meteoalarm.org?geocode=EMMA_ID:DE035"
                    guid: 2d898d0fa322d03a4f641b5c327a4074
                    pubDate: "2025-10-15T04:22:00"
                    region: Kreis Breisgau-Hochschwarzwald und Stadt Freiburg
                    awarenessLevel: 2
                    awarenessType: 4
                    validFrom: "2025-10-15T03:17:00"
                    validUntil: "2025-10-15T08:00:00"
                    language: german
        '500':
          description: Internal server error while fetching weather data
components:
  schemas:
    MeteoAlarmResponse:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string
        language:
          type: string
        ttl:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/MeteoAlarmItem'
    MeteoAlarmItem:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string
        guid:
          type: string
        pubDate:
          type: string
          format: date-time
        region:
          type: string
        awarenessLevel:
          type: integer
        awarenessType:
          type: integer
        validFrom:
          type: string
          format: date-time
          nullable: true
        validUntil:
          type: string
          format: date-time
          nullable: true
        language:
          type: string